### PR TITLE
REST API User signatures

### PR DESCRIPTION
**Pull request by alexeevit**
The API for user's signatures management.

I've made the documentation a bit in advance so we need to wait until the API is released.

I'm not sure if I had to update the postman specs or it is supposed to be generated automatically from the OpenAPI specs.

### CODE REVIEW

**Comment by nel** [comment]
@alexeevit you updated postman spec manually ? AFAICT it's made automatically by release process. Do you confirm @CoCraig ?

**Comment by alexeevit** [comment]
> @alexeevit you updated postman spec manually ? AFAICT it's made automatically by release process. Do you confirm @CoCraig ?

yup, I wasn't sure so I just did it manually.

**Comment by CoCraig** [comment]
Yes, the Postman spec is auto-generated from the swagger spec. We don't have it running on a schedule, but something that is manually triggered and then generated.

**Comment by alexeevit** [comment]
> Yes, the Postman spec is auto-generated from the swagger spec. We don't have it running on a schedule, but something that is manually triggered and then generated.

Oh ok cool, I reverted it

**Comment by grokify** [comment]
The Postman spec is currently created manually using the instructions here:

[specs/README.md](specs/README.md)

**Comment by nel** [comment]
FTR I merged this PR in another PR (could not update this one as it's from another repo), I updated the postman spec at the same time with new process.

**Pull request closed without merging**
