### PR TITLE
Better: Add receive_functional_alerts and receive_configurational_alerts permissions. RD-22879

### PR DESCRIPTION
**Pull request by alexeykondratenko**

### CODE REVIEW

**Comment by brenauj** [comment]
@alexeykondratenko can you provide a screenshot?

**Comment by alexeykondratenko** [comment]
> @alexeykondratenko can you provide a screenshot?

Do you mean postman screenshot?

If yes, here is:

Screenshot 2022-11-17 at 10 08 11
Screenshot 2022-11-17 at 10 07 58

**Comment by brenauj** [comment]
> > @alexeykondratenko can you provide a screenshot?
> 
> Do you mean postman screenshot?
> 
> If yes, here is:
> 
> Screenshot 2022-11-17 at 10 08 11
> 
> Screenshot 2022-11-17 at 10 07 58

I meant preview from swagger editor

**Comment by alexeykondratenko** [comment]
> I meant preview from swagger editor

Here is 

Screenshot 2022-11-17 at 13 57 06

Screenshot 2022-11-17 at 13 56 55

**Review by brenauj — APPROVED** [review]
LGTM :+1:

**Pull request closed without merging**
