### PR TITLE
Add documentation for email credentials updating. RD-18084

### PR DESCRIPTION
**Pull request by alexeevit**
This PR adds documentation for the new endpoint to update credentials of email sources for imap/smtp adapters.
**Please, don't merge it until the feature MR is merged.**

### CODE REVIEW

**Comment by CedricBm** [comment]
It's better to assign the documentation change to the MR reviewer :wink:

**Review by ArtyomIvanov-dev — COMMENTED** [review]
LGTM

**Comment by nel** [comment]
We are waiting for @FabienChaynes for the merge ?

**Comment by alexeevit** [comment]
> We are waiting for @FabienChaynes for the merge ?

We're waiting the feature branch to be tested and merged

**Pull request merged**
