### PR TITLE
Minor: Add POST Contents API auto_submitted field doc RD-25063

### PR DESCRIPTION
**Pull request by ndomenec**

### CODE REVIEW

**Comment by ylecuyer** [comment]
Could you add screenshots of the changes so that I can have an idea of what has been added

**Comment by ndomenec** [comment]
Not sure how to see the actual swagger spec but here's how it looks on [swagger](https://editor.swagger.io/) 

swagger-preview

**Comment by ylecuyer** [comment]
Thanks, LGTM

**Comment by ndomenec** [comment]
Commit was merged FTR

**Pull request closed without merging**
