### PR TITLE
Better: Remove legacy field from interventions schema. RD-20480

### PR DESCRIPTION
**Pull request by brenauj**
Only schema changes so no need to update postman file.

### CODE REVIEW

**Comment by CedricBm** [comment]
LGTM. We may not need to wait for the code deploy day to merge this one, do we?

**Comment by brenauj** [comment]
> LGTM. We may not need to wait for the code deploy day to merge this one, do we?

https://developers.ringcentral.com/engage/digital/api-reference/Interventions/getIntervention the field is not even in the doc yet, shouldn't we at least wait for it to appear there?

**Comment by CedricBm** [comment]
mmh, but this breaking change is supposed to be deployed on January 12. If we wait for the previous doc commit to be deployed and then merge this current one, it would be deployed probably after Jan 12.

Can you coordinate this with Anastasia please?

**Comment by brenauj** [comment]
> mmh, but this breaking change is supposed to be deployed on January 12. If we wait for the previous doc commit to be deployed and then merge this current one, it would be deployed probably after Jan 12.
> 
> Can you coordinate this with Anastasia please?

I checked with her, she asked to merge today

**Pull request merged**
