### PR TITLE
Better: Remove denorm fields from survey response schema now that survey API exist. RD-20265

### PR DESCRIPTION
**Pull request by brenauj**

### CODE REVIEW

**Comment by brenauj** [comment]
I didn't provide screenshots since it's removal only, please tell me if you want one anyway @CedricBm

**Comment by CedricBm** [comment]
You still need to auto-update the postman file, don't you?

**Comment by brenauj** [comment]
> You still need to auto-update the postman file, don't you?
> 
> Or not because it's only about the response format here.

Indeed, nothing to update for postman file

**Comment by CedricBm** [comment]
LGTM

**Pull request merged**
