### PR TITLE
Better: Add Instagram Messaging documentation for Template Messages RD-19647

### PR DESCRIPTION
**Pull request by ndomenec**

### CODE REVIEW

**Comment by ylecuyer** [comment]
Could you add a preview of what it looks like in the end? or a link where it can be viewed?

**Comment by ndomenec** [comment]
Here is how the main changes look like @ylecuyer :
structured_api_overview


ig_messaging_structured_list


ig_messaging_template

**Comment by ylecuyer** [comment]
> Here is how the main changes look like @ylecuyer : structured_api_overview
> 
> ig_messaging_structured_list
> 
> ig_messaging_template

Great thanks

**Comment by ylecuyer** [comment]
LGTM

**Review by ylecuyer — APPROVED** [review]

**Pull request merged**
